-- CRIANDO UM NOVO BANCO DE DADOS EM MYSQL OU MariaDB
CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNOS(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    RA VARCHAR(6),
    STATUS BOOLEAN DEFAULT(TRUE)
);